<?php
$salutation = get_post_meta( $orderID, 'salutation', true );
$greating   = ( $salutation === 'Herr' ? 'geehrter' : 'geehrte' );
$name       = implode( ' ', [
	$salutation,
	get_post_meta( $orderID, 'firstName', true ),
	get_post_meta( $orderID, 'lastName', true ),
] );

$company = utf8_decode(get_option('company'));
$companyWithoutForm = utf8_decode(get_option('companyWithoutForm'));
$companyPhone = get_option('telefon');
$companyColor =  get_option( 'color' );

$paymentModalities = (array)json_decode(get_option('abschlag'));
?>

<table style="max-width: 600px; margin: 50px auto;">
	<tr>
		<td>
			<img src="<?php echo wp_get_attachment_url(get_option('logo'));?>" alt="" width="250">
			<br>
			<br>
			<br>
			<h1 style="color: <?php echo $companyColor;?>">Ihre Rechnung <?php echo $companyWithoutForm; ?></h1>
			<h2 style="color: <?php echo $companyColor;?>">Sehr <?php echo $greating; ?> <?php echo $name; ?>,</h2>
			<p>
				wir möchten uns zunächst nochmal herzlich für das uns entgegen gebrachte Vertrauen bedanken.
			</p>
			<p>
				Anbei erhalten Sie die Rechnung.
			</p>
			<p>
				Für Fragen stehen wir Ihnen gerne telefonisch zur Verfügung. <?php echo $companyPhone;?>
			</p>
			<p>
				<b>Montag - Freitag von <?php echo get_option('openingHours');?></b>
			</p>
			<br>
			<br>
			Mit freundlichen Grüßen<br>
			<h2 style="color: <?php echo $companyColor;?>">Ihr Projektmanagement von <?php echo $companyWithoutForm; ?></h2>
		</td>
	</tr>
</table>