<?php

if ( ! defined( 'DATEPICKER_ASSETS_ADDED' ) || DATEPICKER_ASSETS_ADDED !== true ):
	define( "DATEPICKER_ASSETS_ADDED", true );
	?>

    <!-- Popperjs -->
    <script src="/wp-content/themes/swb/angebote/popper.min.js"
            crossorigin="anonymous"></script>
    <!-- Tempus Dominus JavaScript -->
    <script src="/wp-content/themes/swb/angebote/tempus-dominus.js"
            crossorigin="anonymous"></script>
    <!-- Tempus Dominus Styles -->
    <link href="/wp-content/themes/swb/angebote/tempus-dominus.css"
          rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script>
        let datePickers = {};
    </script>


    <!--    <link rel="stylesheet" type="text/css" href="/wp-content/themes/swb/angebote/datepicker.css">-->
    <!--    <script src="/wp-content/themes/swb/angebote/moment.js"></script>-->
    <!--    <script src="/wp-content/themes/swb/angebote/datepicker.js"></script>-->

<?php endif; ?>

<div class="form-group date text">
    <label for="dcAppointment"><?php echo $inputLabel; ?></label>
    <input autocomplete="off" type="text" id="<?php echo $datePickerId; ?>" name="<?php echo $inputName; ?>"
           value="<?php echo $inputValue ?? ''; ?>"
           class="form-control">
</div>


<script>

    jQuery(document).ready(function () {
        let today = new Date();
        let tomorrow = new Date(today);
        tomorrow.setDate(tomorrow.getDate() + 1)

        datePickers.<?php echo $datePickerId; ?> = new tempusDominus.TempusDominus(document.getElementById('<?php echo $datePickerId; ?>'), {
            localization: {
                today: 'Heute',
                clear: 'Auswahl löschen',
                close: 'Auswahlbox schließen',
                selectMonth: 'Monat wählen',
                previousMonth: 'Letzter Montat',
                nextMonth: 'Nächster Monat',
                selectYear: 'Jahr wählen',
                previousYear: 'Letztes Jahr',
                nextYear: 'Nächstes Jahr',
                selectDecade: 'Jahrzehnt wählen',
                previousDecade: 'Letztes Jahrzent',
                nextDecade: 'Nächstes Jahrzent',
                previousCentury: 'Letztes Jahrhundert',
                nextCentury: 'Nächstes Jahrhundert',
                pickHour: 'Stunde wählen',
                incrementHour: 'Stunde erhöhen',
                decrementHour: 'Stunde verringern',
                pickMinute: 'Minute wählen',
                incrementMinute: 'Minute erhöhen',
                decrementMinute: 'Minute verringern',
                pickSecond: 'Sekunde wählen',
                incrementSecond: 'Sekunde erhöhen',
                decrementSecond: 'Sekunde verringern',
                toggleMeridiem: 'Tageszeit umschalten',
                selectTime: 'Zeit wählen',
                selectDate: 'Datum wählen',
                dayViewHeaderFormat: {month: 'long', year: '2-digit'},
                locale: 'de',
                startOfTheWeek: 1,
            },
            restrictions: {
                //minDate: tomorrow,
            },
            display: {
                viewMode: 'calendar',
                keepOpen: false,
                components: {
                    decades: true,
                    year: true,
                    month: true,
                    date: true,
                    hours: <?php echo $time === true ? 'true' : 'false' ?>,
                    minutes: <?php echo $time === true ? 'true' : 'false' ?>,
                    seconds: false,
	                <?php echo $time === true ? 'useTwentyfourHour: true' : '' ?>
                },
                icons: {
                    time: 'bi bi-clock',
                    date: 'bi bi-calendar',
                    up: 'bi bi-arrow-up',
                    down: 'bi bi-arrow-down',
                    previous: 'bi bi-chevron-left',
                    next: 'bi bi-chevron-right',
                    today: 'bi bi-calendar-check',
                    clear: 'bi bi-trash',
                    close: 'bi bi-x',
                }
            }
        });
    });
</script>
