<?php

if ( ! defined( 'ALLOWED_STEPS_TO_UPLOAD' ) ) {
	define( "ALLOWED_STEPS_TO_UPLOAD", [ 1, 2, 3, 4, 5, 6, 7, 8 ] );
}

$allowUpload      = in_array( $step, ALLOWED_STEPS_TO_UPLOAD, true ) && $allowedToEdit === true;
$orderAttachments = orderAttachments( $order );
?>

<div class="row">
    <div class="col-12">
        <div class="text-center pb-4">
            <h2>Projektuploads</h2>

            <div class="d-flex justify-content-center flex-wrap" id="lightgallery">
				<?php foreach ( $orderAttachments as $attachmentKey => $attachmentMeta ): ?>
					<?php $attachmentIsImage = str_starts_with( $attachmentMeta['type'], 'image' );
					 $attachmentIsPDF = str_contains($attachmentMeta['url'], '.pdf') != 0;
					 $attachmentIsVideo = str_contains($attachmentMeta['url'], '.mp4') != 0 || str_contains($attachmentMeta['url'], '.mov') != 0; ?>
                    <div>
						<?php
						$imageBackground = '';
						if ( $attachmentIsImage ) {
							$imageBackground .= 'background-image: url(' . $attachmentMeta['url'] . '); background-size: cover;';
						} else if ($attachmentIsPDF) {
							$imageBackground .= 'background-image: url(/wp-content/themes/swb/img/icons/PDF_file_icon.svg); background-size: 50%; background-repeat: no-repeat;background-color: #fff;';
						} else if ($attachmentIsVideo) {
							$imageBackground .= 'background-image: url(/wp-content/themes/swb/img/icons/video-icon.svg); background-size: 50%; background-repeat: no-repeat;background-color: #fff;';
						}
						?>
                        <div class="order-attachment" title="<?php echo basename( $attachmentMeta['url'] ); ?>">
                            <a href="<?php echo $attachmentMeta['url']; ?>" class="order-attachment__icon" <?php echo str_contains($attachmentMeta['url'], '.pdf') != 0 || str_contains($attachmentMeta['url'], '.mp4') != 0 || str_contains($attachmentMeta['url'], '.mov') != 0 ? 'data-iframe="true" data-src="'. $attachmentMeta['url']. '"':''; ?>
                               style="<?php echo $imageBackground; ?>"></a>
							<?php if ( checkRoles( [ 'administrator', 'registration', 'director' ] ) ): ?>
                                <a class="order-attachment__delete"
                                   href="<?php echo addOrUpdateUrlParam( [ 'delete-attachment' => $attachmentKey ] ); ?>">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16.971" height="16.971"
                                         viewBox="0 0 16.971 16.971">
                                        <line id="Linie_11" data-name="Linie 11" y2="18"
                                              transform="translate(14.849 2.121) rotate(45)" fill="none" stroke="#000"
                                              stroke-linecap="round" stroke-width="3"/>
                                        <line id="Linie_12" data-name="Linie 12" x2="18"
                                              transform="translate(2.121 2.121) rotate(45)" fill="none" stroke="#000"
                                              stroke-linecap="round" stroke-width="3"/>
                                    </svg>
                                </a>
							<?php endif; ?>
                            <p class="order-attachment__name">
								<?php echo basename( $attachmentMeta['url'] ); ?>
                            </p>
                        </div>
                    </div>
				<?php endforeach; ?>
				<?php if ( $allowUpload === true ): ?>
                    <label class="label--upload" for="orderAttachments">Dateien hinzufügen</label>
					<?php wp_nonce_field( plugin_basename( __FILE__ ), 'orderAttachments_nonce' ); ?>
                    <input type="file" id="orderAttachments" name="orderAttachments[]" value="" size="25" multiple>
				<?php endif; ?>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery-js/1.4.0/js/lightgallery.min.js" integrity="sha512-b4rL1m5b76KrUhDkj2Vf14Y0l1NtbiNXwV+SzOzLGv6Tz1roJHa70yr8RmTUswrauu2Wgb/xBJPR8v80pQYKtQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery-js/1.4.0/css/lightgallery.min.css" integrity="sha512-kwJUhJJaTDzGp6VTPBbMQWBFUof6+pv0SM3s8fo+E6XnPmVmtfwENK0vHYup3tsYnqHgRDoBDTJWoq7rnQw2+g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script type="text/javascript">
	  lightGallery(document.getElementById('lightgallery'), {
        selector: '.order-attachment__icon'
	  });
</script>

<style>
    #adminmenuwrap, #wpadminbar {
	    z-index: 1000;
    }
</style>