<?php
$salutation = get_post_meta( $orderID, 'salutation', true );
$greating   = ( $salutation === 'Herr' ? 'geehrter' : 'geehrte' );
$name       = implode( ' ', [
	$salutation,
	get_post_meta( $orderID, 'firstName', true ),
	get_post_meta( $orderID, 'lastName', true ),
] );

$company = utf8_decode(get_option('company'));
$companyWithoutForm = utf8_decode(get_option('companyWithoutForm'));
$companyPhone = get_option('telefon');
$companyColor =  get_option( 'color' );

$invoiceNumber = get_post_meta($orderID, 'sevdesk_invoice_number', true);
$invoiceDate = date( 'd.m.Y', strtotime( get_post_meta( $orderID, 'sevdesk_invoice_date', true ) ) );

$totalIncl = get_post_meta($orderID, 'totalIncl', true);
$duePaymentPercentage = getDuePercentage($orderID);
$duePayment            = number_format($totalIncl * $duePaymentPercentage / 100, 2, ',', '.');

$reminderDate = date( 'd.m.Y', strtotime( get_post_meta( $orderID, 'sevdesk_reminder_date', true ) ) );
?>

<table style="max-width: 600px; margin: 50px auto;">
	<tr>
		<td>
			<img src="<?php echo wp_get_attachment_url(get_option('logo'));?>" alt="" width="250">
			<br>
			<br>
			<br>
			<h1 style="color: <?php echo $companyColor;?>">Letzte Mahnung <?php echo $invoiceNumber ?></h1>
			<h2 style="color: <?php echo $companyColor;?>">Sehr <?php echo $greating; ?> <?php echo $name; ?>,</h2>
			<p>
				unsere Rechnung <strong><?php echo $invoiceNumber ?></strong> vom <strong><?php echo $invoiceDate?></strong> über den Betrag von <strong><?php echo $duePayment;?></strong> ist weiterhin offen. Leider konnten wir bis heute keinen Zahlungseingang feststellen. Auch auf unsere 2. Mahnung vom <strong><?php echo $reminderDate;?></strong> haben Sie bis heute weder schriftlich noch telefonisch reagiert.<br>
				<br>
				Wir bitte Sie letztmalig darum den fälligen Betrag innerhalb der nächsten sieben Tage auf unser Bankkonto zu überweisen. Sollten wir bis zum angegebenen Termin keinen Zahlungseingang feststellen, geben wir die Forderung an unser Inkassobüro weiter.<br>
				<br>
				Bei Rückfragen können Sie sich jederzeit an uns wenden.<br>
			</p>
			Mit freundlichen Grüßen,<br>
			<h2 style="color: <?php echo $companyColor;?>"><?php echo $companyWithoutForm; ?></h2>
		</td>
	</tr>
</table>