<?php
$salutation = get_post_meta( $orderID, 'salutation', true );
$greating   = ( $salutation === 'Herr' ? 'geehrter' : 'geehrte' );
$name       = implode( ' ', [
	$salutation,
	get_post_meta( $orderID, 'firstName', true ),
	get_post_meta( $orderID, 'lastName', true ),
] );

$company = utf8_decode(get_option('company'));
$companyWithoutForm = utf8_decode(get_option('companyWithoutForm'));
$companyPhone = get_option('telefon');
$companyColor =  get_option( 'color' );

$invoiceNumber = get_post_meta($orderID, 'sevdesk_invoice_number', true);
$invoiceDate = date( 'd.m.Y', strtotime( get_post_meta( $orderID, 'sevdesk_invoice_date', true ) ) );
?>

<table style="max-width: 600px; margin: 50px auto;">
	<tr>
		<td>
			<img src="<?php echo wp_get_attachment_url(get_option('logo'));?>" alt="" width="250">
			<br>
			<br>
			<br>
			<h1 style="color: <?php echo $companyColor;?>">Zahlungserinnerung <?php echo $invoiceNumber ?></h1>
			<h2 style="color: <?php echo $companyColor;?>">Sehr <?php echo $greating; ?> <?php echo $name; ?>,</h2>
			<p>
				vielleicht haben Sie im hektischen Alltag übersehen, dass Sie Ihre Rechnung mit der Rechnungsnummer <strong><?php echo $invoiceNumber ?></strong> vom <strong><?php echo $invoiceDate;?></strong> noch nicht beglichen haben? Leider haben wir bislang keinen Zahlungseingang verbuchen können.<br>
				<br>
				Wir sind uns sicher, dass es sich hierbei um ein Versehen handelt.<br>
				<br>
				Wir bitten Sie den fälligen Betrag in den nächsten sieben Tagen zu überweisen.<br>
				<br>
				Sollten Sie die Zahlung bereits veranlasst haben, dann bitten wir Sie diesem Schreiben keine weitere Beachtung zu schenken.
			</p>
			Mit freundlichen Grüßen,<br>
			<h2 style="color: <?php echo $companyColor;?>"><?php echo $companyWithoutForm; ?></h2>
		</td>
	</tr>
</table>