<div class="my-1 mt-2"><label>AC Monteur und Termin auswählen *</label></div>
<?php
$inputLabel    = 'AC Termin';
$inputName     = 'ac_appointment';
$randomId      = md5( microtime() );
$datePickerId  = "${inputName}_${randomId}";
$acTechnicians = acTechnicians();
$wpNonce       = wp_create_nonce( 'wp_rest' );
?>
<div class="form-group text">
    <label for="ac_technician">AC Monteur</label>
    <select id="ac_technician" name="ac_technician" class="form-control">
        <option></option>
		<?php $selectedAcTechnician = get_post_meta( $order->ID, 'ac_technician', true ); ?>
		<?php foreach ( $acTechnicians as $acTechnician ): ?>
            <option<?php echo( $acTechnician->ID === $selectedAcTechnician ? ' selected' : '' ); ?>
                    value="<?php echo $acTechnician->ID; ?>">
				<?php echo esc_html( $acTechnician->display_name ); ?>
            </option>
		<?php endforeach; ?>
    </select>
</div>

<?php include template( 'global/datepicker' ); ?>

<script>
    jQuery('#ac_technician').change(function (event) {
        let userId = event.currentTarget.value;
        if (userId === undefined || userId === '' || userId === null || userId === 0) {
            return;
        }

        jQuery.get(`/wp-json/orders/v1/ac-user-events/${userId}?_wpnonce=<?php echo $wpNonce; ?>`, function (response) {
            let datePicker = datePickers.<?php echo $datePickerId; ?>;
            datePicker.updateOptions({
                restrictions: {
                    disabledDates: response
                },
            });
            datePicker.show();
        });
    });
</script>

