<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
					<?php include template( 'step-4/dc-appointment' ); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
					<?php include template( 'step-6/ac-appointment' ); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-lg-6">
					<?php include template( 'step-2/personal-and-contact-info' ); ?>
                </div>
                <div class="col-12 col-lg-6">
					<?php include template( 'step-2/pv-and-offer-info' ); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
					<?php include template( 'global/notes' ); ?>
                </div>
	            <div class="col-12">
		            <?php include template( 'global/customer-notes' ); ?>
	            </div>
            </div>
        </div>
    </div>

	<?php if (checkRoles(['qa_manager', 'director', 'administrator'])):?>
		<?php include template( 'global/qa' ); ?>
	<?php endif;?>
	<?php include template( 'global/uploader' ); ?>
</div>