<?php

$firstBilling  = get_post_meta( $order->ID, 'first-billing', true );
$secondBilling = get_post_meta( $order->ID, 'second-billing', true );

$allowFirstBilling  = $step > 4;
$allowSecondBilling = $step > 6;

$allowActions = ( (int) $step > 4 && empty( $firstBilling ) ) || ( (int) $step > 6 && empty( $secondBilling ) );

//INVOICE FILES
$invoiceId             = get_post_meta( $order->ID, 'sevdesk_invoice_id', true );
$invoiceRenderFileName = get_post_meta( $order->ID, 'sevdesk_invoice_render', true );
$invoiceFileName       = get_post_meta( $order->ID, 'sevdesk_invoice_pdf', true );

//REMINDER FILES
$reminderRenderFileName = get_post_meta( $order->ID, 'sevdesk_reminder_render', true );
$reminderFileName       = get_post_meta( $order->ID, 'sevdesk_reminder_pdf', true );
$reminderDate           = get_post_meta( $order->ID, 'sevdesk_reminder_date', true );
$dueDays                = get_option( 'due_days' );

$invoiceSentViaSevdesk = get_post_meta( $order->ID, 'sevdesk_sent_via_sevdesk', true );


if ( $invoiceId && empty( $invoiceFileName ) ) {
	// Wenn eine RechnungsID existiert und diese den Status 200 hat, wurde sie versendet
	$invoice           = getSevdeskInvoice( $order->ID );
	$invoiceStatusSent = $invoice['objects'][0]['status'] === '200';

	if ( $invoiceStatusSent ) {
		update_post_meta( $order->ID, 'sevdesk_sent_via_sevdesk', 'on' );
		$invoiceDate = date( "Y-m-d", strtotime( $invoice['objects'][0]['invoiceDate'] ) );
		update_post_meta( $order->ID, 'first-billing', $invoiceDate );

		$paymentModalitiesArray = (array) json_decode( get_option( 'abschlag' ) );
		update_post_meta( $order->ID, 'sevdesk_payment_due', array_keys( $paymentModalitiesArray )[0] );
		update_post_meta( $order->ID, 'sevdesk_invoice_render', 'off' );
		update_post_meta( $order->ID, 'sevdesk_invoice_date', $invoice['objects'][0]['sendDate'] );

		//generateSevdeskInvoicePdf( $order->ID );
	} else {
		update_post_meta( $order->ID, 'sevdesk_sent_via_sevdesk', 'off' );
	}
}

?>

<?php include template( 'global/header' ); ?>
<?php if ( isset( $_GET['edit'] ) && $_GET['edit'] === 'on' ): ?>
	<div class="row">
		<div class="col-12 col-lg-6">
			<?php include template( 'step-2/personal-info' ); ?>
		</div>
		<div class="col-12 col-lg-6">
			<?php include template( 'step-1/contact-info' ); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<?php include template( 'step-1/pv-information' ); ?>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<?php include template( 'step-1/offer-information' ); ?>
		</div>
	</div>
	<input type="hidden" name="allow-edit-in-step-3" value="on"/>
<?php else: ?>
	<div class="project__controlling" id="sevdesk">
		<div class="container">
			<div class="row justify-content-md-center">
				<div class="col-8">

					<?php if ( ! empty( $invoiceFileName ) || $invoiceSentViaSevdesk === 'on' ):

						$funding = get_post_meta( $order->ID, 'status', true ) === 'funding';
						$totalIncl = get_post_meta( $order->ID, 'totalIncl', true );
						$overDue = getOverDue( $order->ID );
						$dateToMonitor = get_post_meta($order->ID, 'sevdesk_date_to_monitor', true);
						if(is_array($dateToMonitor)) {
							$dateToMonitorType = $dateToMonitor['key'];
							$dateToMonitorDate =  $dateToMonitor['date'];

							if($dateToMonitorType === 'Speicher Versandtermin') {
								$dueDays += get_option('buffer_days');
							}
						}
						$duePaymentPercentage = getDuePercentage( $order->ID );


						if ( getSevdeskInvoice( $order->ID ) !== false ) {
							$response   = getSevdeskInvoice( $order->ID );
							$paidAmount = (int) $response['objects'][0]['paidAmount'];
							$sumGross   = (int) $response['objects'][0]['sumGross'];

							$duePayment            = $sumGross * $duePaymentPercentage / 100;
							$alreadyPaidPercentage = 100 / $duePayment * $paidAmount;
							$alreadyPaidPercentageFromTotal = 100 / $totalIncl * $paidAmount;
							$paymentCompleted      = $paidAmount >= $duePayment;

							update_post_meta( $order->ID, 'sevdesk_paid_amount', number_format( $paidAmount, 2, '.', '' ) );
							if ( $paidAmount >= $duePayment ) {
								update_post_meta( $order->ID, 'sevdesk_paid_due_amount', true );
								delete_post_meta( $order->ID, 'sevdesk_reminder_render' );
							} else {
								delete_post_meta( $order->ID, 'sevdesk_paid_due_amount' );
							}

							update_post_meta(
								$order->ID,
								'sevdesk_paid_amount_percentage',
								( $paidAmount > 0 && $duePayment > 0 ) ? (100 / $duePayment * $paidAmount) : 0
							);

							if ( $paidAmount !== $duePayment && $overDue ) {
								update_post_meta( $order->ID, 'sevdesk_ready_to_remind', 'true' );
							} else {
								delete_post_meta( $order->ID, 'sevdesk_ready_to_remind' );
							}
						}

						$dueAmountPaid = metadata_exists( 'post', $order->ID, 'sevdesk_paid_due_amount' );
						$overDue       = $overDue && ! $dueAmountPaid;
						?>

						<div
							class="order-card card payment <?php echo ! $funding ?: 'card--funding'; ?> <?php echo ! $overDue ?: 'card--overdue'; ?>"
							<?php echo !empty($dateToMonitor) ? 'data-overdue="Zahlungsziel von ' . $dueDays . ' Tagen überschritten seit ' . $dateToMonitorType . ' am ' . date('d.m.Y', strtotime($dateToMonitorDate)) . '"' : '' ; ?>>
							<div class="row relative">
								<div class="col-12">
									<div class="text-center mb-1">
										<?php if ( $funding ): ?>
											<div class="funding-info">
												Bei diesem Auftrag handelt es sich um eine Finanzierung.<br>
												Die Rechnung wird nicht automatisch versendet.
											</div>
										<?php endif; ?>
										<strong>Gesamtbetrag <?php echo number_format( $sumGross, 2, ',', '.' ); ?>
											€</strong>
									</div>
									<div class="offset-1 col-10">
										<div class="progress-bar mb-3"
										     data-total="Gesamt: <?php echo number_format( $sumGross, 2, ',', '.' ); ?> €">
											<div class="progress progress--due"
											     style="width: <?php echo $duePaymentPercentage; ?>%">
												<?php if ( $dueAmountPaid ) : ?>
													<div class="progress progress--finished">
														<svg width="18" height="18" viewBox="0 0 18 18" fill="none"
														     xmlns="http://www.w3.org/2000/svg">
															<circle cx="9" cy="9" r="9" fill="#409749"/>
															<path d="M4 10.4444L8.28571 14L14 4.5" stroke="white"
															      stroke-width="2"/>
														</svg>
														Zahlung vollständig erhalten
													</div>
												<?php elseif ( $paidAmount > 0 ) : ?>
													<div class="progress progress--done" data-received="Erhalten <?php echo number_format($alreadyPaidPercentageFromTotal, 0);?>%"
													     style="width: <?php echo $alreadyPaidPercentage; ?>%">
														<?php echo number_format( $paidAmount, 2, ',', '.' ); ?> €
													</div>
												<?php else : ?>
													<div class="progress progress--zero">
														<svg width="18" height="18" viewBox="0 0 18 18" fill="none"
														     xmlns="http://www.w3.org/2000/svg">
															<circle cx="9" cy="9" r="9" fill="#FF5959"/>
															<path
																d="M9.94815 5.27273L9.78196 11.3835H8.2223L8.05185 5.27273H9.94815ZM9.00213 14.1108C8.72088 14.1108 8.4794 14.0114 8.2777 13.8125C8.07599 13.6108 7.97656 13.3693 7.9794 13.0881C7.97656 12.8097 8.07599 12.571 8.2777 12.3722C8.4794 12.1733 8.72088 12.0739 9.00213 12.0739C9.27202 12.0739 9.50923 12.1733 9.71378 12.3722C9.91832 12.571 10.022 12.8097 10.0249 13.0881C10.022 13.2756 9.9723 13.4474 9.87571 13.6037C9.78196 13.7571 9.65838 13.8807 9.50497 13.9744C9.35156 14.0653 9.18395 14.1108 9.00213 14.1108Z"
																fill="white"/>
														</svg>
														Noch keine Zahlung erhalten.
													</div>
												<?php endif; ?>
												<div class="progress__info" data-due="Fällig <?php echo number_format($duePaymentPercentage, 0);?>%">
													<?php echo number_format( $duePayment, 2, ',', '.' ); ?> €
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="col-12">
									<?php if ( ! empty( $invoiceFileName ) ): ?>
										<div class="d-flex align-items-center file">
											<a target="_blank" class="order-attachment__icon" data-iframe="true"
											   href="/wp-content/uploads/orders-attachments/<?php echo $order->ID . '/' . $invoiceFileName; ?>"></a>
											<div>
												<strong><?php echo $invoiceFileName; ?></strong><span>Rechnung versendet am <?php echo date('d.m.Y', strtotime(get_post_meta(get_the_ID(), 'sevdesk_invoice_date', true))); ?></span>
											</div>
										</div>
									<?php else: ?>
										<div>
											<strong><?php echo $invoiceFileName; ?></strong><span>Rechnung versendet am <?php echo $firstBilling; ?></span>
										</div>
									<?php endif; ?>
									<?php if ( $reminderFileName ): ?>
										<?php
										$prefix         = 'sevdesk_reminder_pdf';
										$all_post_metas = get_post_meta( $order->ID );
										$i              = 0;
										foreach ( $all_post_metas as $meta_key => $meta_value ) :
											$reminderFileName = get_post_meta( $order->ID, $meta_key, true );
											if ( strpos( $meta_key, $prefix ) === 0 ) :
												?>
												<div class="d-flex align-items-center mt-2 file">
													<a target="_blank" class="order-attachment__icon" data-iframe="true"
													   href="/wp-content/uploads/orders-attachments/<?php echo $order->ID . '/' . $reminderFileName; ?>"></a>
													<div>
														<strong>
															<?php echo $reminderFileName; ?>
														</strong>
														<span>
													<?php if ( $i > 0 ) : ?>
														<?php echo $i ?>. Mahnung versendet
														am <?php echo date('d.m.Y', strtotime(get_post_meta($order->ID, 'sevdesk_reminder_date-' . $i, true))) ;?>
													<?php else : ?>
														Zahlungserinnerung versendet am <?php echo date('d.m.Y', strtotime(get_post_meta($order->ID, 'sevdesk_reminder_date', true)));?>
													<?php endif; ?>
															</span>
													</div>
												</div>
												<?php $i ++;
											endif;
										endforeach; ?>
									<?php elseif ( $reminderRenderFileName ): ?>
										<div class="d-flex align-items-center mt-1">
											<a target="_blank" class="order-attachment__icon"
											   style="background-image: url('/wp-content/uploads/orders-attachments/<?php echo $order->ID . '/' . $reminderRenderFileName; ?>')"
											   href="/wp-content/uploads/orders-attachments/<?php echo $order->ID . '/' . $reminderRenderFileName; ?>"></a>
											Zahlungserinnerung Entwurf
										</div>
									<?php endif; ?>
								</div>
							</div>
						</div>
					<?php elseif ( empty( $invoiceId ) ): ?>
						<div class="d-flex align-items-center">
							<div class="form-group text mr-1 mb-0" style="width: 100%;">
								<label for="sevdesk_invoice_id">Sevdesk Rechnungs ID</label>
								<input id="sevdesk_invoice_id" name="sevdesk_invoice_id" class="form-control"/>
							</div>
							<button class="button-primary button-sevdesk"
							        formaction="post.php?controlling=on&connectInvoice=on">Rechnung aus Sevdesk koppeln
							</button>
						</div>
					<?php endif; ?>
					<div class="row relative">
						<div class="col-12">
							<?php include template( 'step-4/dc-appointment' ); ?>
						</div>
						<?php if ( $allowFirstBilling && ! empty( $firstBilling ) ): ?>

						<?php elseif ( is_array( $invoiceRenderFileName ) ) : ?>
							<div class="order-card card controlling-card">
								<div class="card-body">
									Rechnungsentwurf erstellt
									<div>
										<?php foreach ( $invoiceRenderFileName as $filename ): ?>
											<a target="_blank" class="order-attachment__icon"
											   style="background-image: url('/wp-content/uploads/orders-attachments/<?php echo $order->ID . '/' . $filename; ?>')"
											   href="/wp-content/uploads/orders-attachments/<?php echo $order->ID . '/' . $filename; ?>"></a>
										<?php endforeach; ?>
									</div>
								</div>
							</div>
						<?php endif; ?>
					</div>

					<div class="row relative">
						<div class="col-12">
							<?php include template( 'step-6/ac-appointment' ); ?>
						</div>
						<?php if ( $allowSecondBilling && ! empty( $secondBilling ) ): ?>
							<div class="order-card card controlling-card">
								<div class="card-body">
									In Rechnung gestellt am <?php echo $secondBilling; ?>
								</div>
							</div>
						<?php endif; ?>
					</div>
					<div class="row">
						<div class="col-6">
							<?php include template( 'step-2/personal-and-contact-info' ); ?>
						</div>
						<div class="col-6">
							<?php include template( 'step-2/pv-and-offer-info' ); ?>
						</div>
					</div>
					<div class="row">
						<div class="col-12">
							<?php include template( 'global/notes' ); ?>
						</div>
					</div>
					<?php include template( 'global/uploader' ); ?>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>

<script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery-js/1.4.0/js/lightgallery.min.js"
        integrity="sha512-b4rL1m5b76KrUhDkj2Vf14Y0l1NtbiNXwV+SzOzLGv6Tz1roJHa70yr8RmTUswrauu2Wgb/xBJPR8v80pQYKtQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery-js/1.4.0/css/lightgallery.min.css"
      integrity="sha512-kwJUhJJaTDzGp6VTPBbMQWBFUof6+pv0SM3s8fo+E6XnPmVmtfwENK0vHYup3tsYnqHgRDoBDTJWoq7rnQw2+g=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
<script type="text/javascript">
  lightGallery(document.getElementById('sevdesk'), {
    selector: '.order-attachment__icon'
  });
</script>

