<?php

$filledDashboard = false;

?>

<link rel="stylesheet" type="text/css" href="/wp-content/themes/swb/css/sass/steps.css">
<script src="https://cdn.jsdelivr.net/gh/vdw/HideSeek@master/jquery.hideseek.min.js"></script>

<script>
  jQuery(document).ready(function () {
    jQuery('#search').hideseek( {
      headers: '.dashboard__header'
    });


	<?php if ( checkRoles( [ 'administrator', 'director', 'director-ip' ] ) ) : ?>
    jQuery.ajax({
      type: "POST",
      url: "/<?php echo get_option('icalhash')?>/ical.php?calendar=dc",
    });

    jQuery.ajax({
      type: "POST",
      url: "/<?php echo get_option('icalhash')?>/ical.php?calendar=ac",
    });
	<?php endif;?>

});
</script>
<div class="postbox" style="margin: 2rem 20px 0 0; padding: 1rem 2rem">
	<div class="dashboard__search d-flex align-items-center">
		<svg xmlns="http://www.w3.org/2000/svg" width="34.585" height="33.853" viewBox="0 0 34.585 33.853">
			<g id="Gruppe_1" data-name="Gruppe 1" transform="translate(0.301 -0.359)">
				<g id="Ellipse_1" data-name="Ellipse 1" transform="translate(-0.301 0.359)" fill="none" stroke="#4ca7f8" stroke-linecap="round" stroke-width="3">
					<ellipse cx="14.5" cy="14" rx="14.5" ry="14" stroke="none"/>
					<ellipse cx="14.5" cy="14" rx="12.5" ry="12" fill="none"/>
				</g>
				<path id="Pfad_1" data-name="Pfad 1" d="M1273.274,177.184l-7.993-7.993" transform="translate(-1241.819 -145.801)" fill="none" stroke="#4ca7f8" stroke-linecap="round" stroke-width="3"/>
			</g>
		</svg>
		<input id="search" name="search" placeholder="Suche nach Verkäufer, Kunde, Ort etc." type="text" data-list=".default_list" autocomplete="off">
	</div>
    <div class="container dashboards">
	    <?php $filledDashboard = registrationDashboard(); ?>
		<?php $filledDashboard = pvScoutDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = projectPlanningDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = dcSchedulingDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = wpMontageTerminierung() || $filledDashboard; ?>
		<?php $filledDashboard = ÖL() || $filledDashboard; ?>
		<?php $filledDashboard = GAS() || $filledDashboard; ?>
		<?php $filledDashboard = dcAssemblyDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = dcAssemblyDoneDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = acSchedulingDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = acAssemblyDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = defectsAssemblyDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = opDefectsAssemblyDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = finishedOrdersDashboard() || $filledDashboard; ?>
		<?php $filledDashboard = PROCUREMENTGOODSDELIVERY() || $filledDashboard; ?>
		<?php $filledDashboard = dispo() || $filledDashboard; ?>
		<?php $filledDashboard = NACHTRAG() || $filledDashboard; ?>
		<?php $filledDashboard = qualityDashboard2('Qualitätssicherung', 'dashboards/section', $filter = 'qacall') || $filledDashboard; ?>

		<?php $filledDashboard = firstBillingDashboard() || $filledDashboard; ?>
	    <?php $start = microtime(true);?>
		<?php $filledDashboard = secondBillingDashboard() || $filledDashboard; ?>
	    <?php echo $time_elapsed_secs = microtime(true) - $start;?>

		<?php // $filledDashboard = registeredDashboard() || $filledDashboard; ?>
		<?php // $filledDashboard = registrationDoneDashboard() || $filledDashboard; ?>
		<?php if ( $filledDashboard !== true ): ?>
			<?php include template( 'done/message' ); ?>
		<?php endif; ?>
    </div>
</div>