<?php

$filledDashboard = false;

?>

<link rel="stylesheet" type="text/css" href="/wp-content/themes/swb/css/sass/steps.css">
<?php /*
<script src="https://cdn.jsdelivr.net/gh/vdw/HideSeek@master/jquery.hideseek.min.js"></script>

<script>
  jQuery(document).ready(function () {
    jQuery('#search').hideseek( {
      headers: '.dashboard__header'
    });


	<?php if ( checkRoles( [ 'administrator', 'director', 'director-ip' ] ) ) : ?>
    jQuery.ajax({
      type: "POST",
      url: "/<?php echo get_option('icalhash')?>/ical.php?calendar=dc",
    });

    jQuery.ajax({
      type: "POST",
      url: "/<?php echo get_option('icalhash')?>/ical.php?calendar=ac",
    });
	<?php endif;?>

});
</script>
*/?>
<div class="postbox" style="margin: 2rem 20px 0 0; padding: 1rem 2rem">
	<div class="inside">
		<?php /*
		<div class="dashboard__search d-flex align-items-center">
			<svg xmlns="http://www.w3.org/2000/svg" width="34.585" height="33.853" viewBox="0 0 34.585 33.853">
				<g id="Gruppe_1" data-name="Gruppe 1" transform="translate(0.301 -0.359)">
					<g id="Ellipse_1" data-name="Ellipse 1" transform="translate(-0.301 0.359)" fill="none" stroke="#4ca7f8" stroke-linecap="round" stroke-width="3">
						<ellipse cx="14.5" cy="14" rx="14.5" ry="14" stroke="none"/>
						<ellipse cx="14.5" cy="14" rx="12.5" ry="12" fill="none"/>
					</g>
					<path id="Pfad_1" data-name="Pfad 1" d="M1273.274,177.184l-7.993-7.993" transform="translate(-1241.819 -145.801)" fill="none" stroke="#4ca7f8" stroke-linecap="round" stroke-width="3"/>
				</g>
			</svg>
			<input id="search" name="search" placeholder="Suche nach Verkäufer, Kunde, Ort etc." type="text" data-list=".default_list" autocomplete="off">
		</div>
	    */ ?>
	    <div class="container dashboards pb-2">
		    <?php if(checkRoles(['administrator', 'director'])) :?>
			    <div class="default_list">
				    <h1>Leads Hochladen <small style="font-weight: 100; font-size: 16px">(.EML, .VCF)</small></h1>
				    <?php echo do_shortcode('[vcf_upload]'); ?>
			    </div>
		    <?php endif;?>

			<?php $filledDashboard = openLeadsDashboard(); ?>

			<?php if ( $filledDashboard !== true ): ?>
				<?php include template( 'done/message' ); ?>
			<?php endif; ?>
	    </div>
	</div>
</div>

<script>
  jQuery(document).ready( function($) {
    $('.lead__header').click(function() {
      $(this).toggleClass('lead__header--active');
    });
    $('.lead__header select').click(function(e) {
      e.stopPropagation();
    });

    var uploadForm = $('#upload-form');

    uploadForm.submit(function (event) {
      event.preventDefault();
      var formData = new FormData($(this)[0]);
      $.ajax({
        url: ajaxurl,
        type: 'POST',
        data: formData,
        processData: false,
        contentType: false,
        success: function (response) {
          $('#response').html(response);
          setTimeout(function () {
            window.location = window.location;
          }, 2000);
        },
        error: function (jqXHR, textStatus, errorThrown) {
          $('#response').html('<div class="error">An error occurred while uploading the files.</div>');
        }
      });
    });

    uploadForm.on('change', function () {
      var numFiles = $('input', this)[0].files.length;
      $('.label--upload').text(numFiles + ' Dateien ausgewählt');
    });

    $('.form-lead-notes').submit( function (e) {
      e.preventDefault();
      var leadNotesForm = $(this);

      // AJAX request to save note_leads meta
      $.ajax({
        url: ajaxurl,
        type: 'POST',
        data: leadNotesForm.serialize() + '&action=updateLeadNotes',
        success: function(response) {
          window.location = window.location;
        },
        error: function(xhr, status, error) {
          console.log('Error saving note leads meta: ' + error);
        }
      });
    });

    $('.form-lead-cancel').submit( function (e) {
      e.preventDefault();
      var leadForm = $(this);

      // AJAX request to save note_leads meta
      $.ajax({
        url: ajaxurl,
        type: 'POST',
        data: leadForm.serialize() + '&action=cancelLead',
        success: function(response) {
          window.location = window.location;
        },
        error: function(xhr, status, error) {
          console.log('Error saving note leads meta: ' + error);
        }
      });
    });

    $('.lead__selector select').on('change', function (event) {
      var selectElement = $(this);
      var authorId = $(this).val();
      var postId = $(this).attr('data-postid');
      $.ajax({
        url: ajaxurl,
        type: 'POST',
        data: {
          action: 'set_seller',
          author_id: authorId,
          post_id: postId
        },
        success: function (response) {
          var selectContainer = selectElement.closest('.lead');
          console.log(selectContainer)
          selectContainer.addClass('order-assigned');
        },
        error: function (jqXHR, textStatus, errorThrown) {
          console.log('An error occurred while setting the author ID.');
        }
      });
    });
  });
</script>