<?php
#test
$leadEmail = '';
if($mailArray = (array)get_post_meta($lead->ID, 'lead_email', true)) {
	$leadEmail = $mailArray['default'][0];
}

$leadPhone = '';
if($phoneArray = (array)get_post_meta($lead->ID, 'lead_phone', true)) {
	$leadPhone = $phoneArray['default'][0];
}

$leadAddress = '';
$addressStreet = '';
$addressPostal = '';
$addressCity = '';
if($addressArray = (array)get_post_meta($lead->ID, 'lead_address', true)) {
	$leadAddress = $addressArray['default'][0];
	$addressStreet = $addressArray['default'][0]->street;
	$addressPostal = $addressArray['default'][0]->zip;
	$addressCity = $addressArray['default'][0]->city;
}

$emlLead = get_post_meta($lead->ID, 'lead_eml', true);

$leadFirstName = get_post_meta($lead->ID, 'lead_firstName', true);
$leadLastName = get_post_meta($lead->ID, 'lead_lastName', true);

$leadName = get_post_meta($lead->ID, 'lead_name', true);
$leadOrganization = get_post_meta($lead->ID, 'lead_organization', true);

$author_id = $lead->post_author;
$leadStatus = get_post_meta($lead->ID, 'lead_status', true);
$leadOrder = get_post_meta($lead->ID, 'lead_order', true);

$leadNote = get_post_meta($lead->ID, 'lead_note', true);

$leadStatusString = '';
if($leadStatus === 'assigned') {
	$leadStatusString = 'Verkäufer zugewiesen';
} else if($leadStatus === 'done') {
	$leadStatusString = 'Angebot erstellt';
} else if($leadStatus === 'cancelled') {
	$leadStatusString = 'Lead storniert';
}else {
	$leadStatusString = 'Offen';
}
#lead_organization
#lead_note

?>
<?php // echo get_post_meta( $lead->ID, 'lead_eml_body', true );?>
<div class="lead <?php echo ($leadStatus && !checkRoles('seller')) || ($leadStatus === 'done' || $leadStatus === 'cancelled') ? 'order-'.$leadStatus: '';?>">
	<div class="lead__header">
		<div class="d-flex justify-content-between align-items-center">
			<div><strong>#<?php echo $lead->ID; ?></strong> | <?php echo get_the_title($lead->ID);?> | Datum: <?php echo get_the_date("d.m.Y", $lead->ID);?>
				<br>Status: <strong><?php echo $leadStatusString;?></strong>
			</div>

			<?php if(checkRoles(['administrator', 'director'])):?>
			<div class="lead__selector form-group text">
				<label>Verkäufer</label>
				<select name="" id="" data-postid="<?php echo $lead->ID;?>" class="form-control">
					<option disabled value="" <?php echo !$leadStatus ? 'selected' : '';?>>Bitte auswählen</option>
					<?php

					$args = array(
						'role'    => 'seller',
						'orderby' => 'display_name',
						'order'   => 'ASC'
					);
					$users = get_users( $args );

					foreach ( $users as $user ) {
						echo '<option value="' .$user->ID . '"' . ((int)$author_id === (int)$user->ID ? ' selected' : '') . '>' . esc_html( $user->display_name ) /*. ' [' . esc_html( $user->user_email )*/ . '</option>';
					}

					?>
				</select>
			</div>
			<?php elseif (checkRoles('seller')):?>
			<div class="lead-forms d-flex">
				<form target="_blank" method="post" action="/Angebotsformular/" class="mr-2">
					<input type="hidden" name="lead_id" value="<?php echo $lead->ID;?>" />
					<button class="button-primary" type="submit">Angebot erstellen</button>
				</form>
				<form method="post" class="form-lead-cancel">
					<input type="hidden" name="lead_id" value="<?php echo $lead->ID;?>" />
					<button class="button-secondary" type="submit">Lead Stornieren</button>
				</form>
			</div>
			<?php endif;?>
		</div>
	</div>
	<div class="lead__infos">
		<?php if($leadOrder):?>
		<div class="lead__order">
			<h2>Aus Lead erstelltes Angbot</h2>
			<a class="button button-primary" href="<?php echo get_edit_post_link($leadOrder);?>"><?php echo '#' . $leadOrder . ' ' . get_the_title($leadOrder);?></a>
		</div>
		<?php endif;?>
		<h2>Lead Informationen</h2>
		<?php if ($emlLead) :?>
			<?php // echo strip_tags(get_post_meta($lead->ID, 'lead_eml_body', true), '<table></table><td></td><tr></tr>');?>
			<?php
				$emailBody = get_post_meta($lead->ID, 'lead_eml_body', true);
				$emailBodyWithoutStyle = preg_replace( '/<style\\b[^>]*>(.*?)<\\/style>/s', '', $emailBody );
				$cleanedEmailBody = strip_tags($emailBodyWithoutStyle, '<div><table><tbody><thead><th><tr><td><p><a><img><ul><ol><li><br><strong><em>');
				echo $cleanedEmailBody;
			?>
			<h2>Lead Uploads</h2>
			<?php if($attachments = get_post_meta($lead->ID, 'lead_eml_attachments', true)):?>
				<?php foreach ($attachments as $attachment) :?>
					<?php $attachmentIcon = 'download-file.svg';
						if(str_contains($attachment['url'], '.pdf') != 0){
							$attachmentIcon = 'PDF_file_icon.svg';
						} else if (str_contains($attachment['url'], '.csv') != 0) {
							$attachmentIcon = 'csv_file.svg';
						} else if (str_contains($attachment['url'], '.vcf') != 0) {
							$attachmentIcon = 'vcf_file.svg';
						}
					?>
				<a class="d-inline-flex align-items-center order-attachment__icon order-attachment__icon--item pr-3" href="<?php echo $attachment['url']; ?>" target="_blank">
					<div class="d-flex align-items-center justify-content-center m-3">
						<img width="50" src="/wp-content/themes/swb/img/icons/<?php echo $attachmentIcon; ?>">
					</div>
						<span>
							<?php echo $attachment['filename'];?>
						</span>
					</a>
			<?php endforeach; ?>
			<?php endif; ?>
		<?php else : ?>
			<?php echo $leadName; ?><br>
			<?php echo $leadOrganization; ?>
			<br>
			<?php echo $leadEmail; ?>
			<br>
			<?php echo $leadPhone; ?><br>
			Adresse: <?php echo $addressStreet;?>, <?php echo $addressPostal;?>, <?php echo $addressCity;?><br><br>
			<?php echo
			str_replace("[", "<br>[", $leadNote);?>
		<?php endif;?>
		<?php $leadNotes = getLeadNotes( $lead->ID );?>

		<h2 class="mt-3">Lead Anmerkungen</h2>
		<?php if($leadNotes):?>
		<?php foreach ( $leadNotes as $note ): ?>
			<?php

			$noteClass = '';
			$message = '';

			?>
			<div class="note <?php echo (isset($note['noteType']) ? $note['noteType'] :''); ?>">
				<span class="note__author"><?php echo $note['author'] ?>:</span>
				<span class="note__text"><?php echo $note['message']; ?></span>
				<span class="note__date"><small><?php echo $note['date'] ?></small></span>
			</div>
		<?php endforeach; ?>
		<?php endif; ?>

		<div class="mt-2 form-group text">
			<form method="post" action="" class="form-lead-notes">
				<label for="lead_notes">Anmerkungen zum Lead</label>
				<textarea name="lead_notes" id="lead_notes" cols="30" rows="5" class="form-control"></textarea>
				<input type="hidden" name="lead_id" value="<?php echo $lead->ID;?>">
				<button class="button-secondary mt-2" type="submit">Speichern</button>
			</form>
		</div>
	</div>
</div>



