<?php
$step                 = (int) ( $options['step'] ?? null );
$forceControllingView = (bool) ( $options['forceControllingView'] ?? false );

?>

<div class="row">
    <div class="col-12 default_list">
	    <div class="dashboard__header">
		    <h1><?php echo $title; ?> <small style="font-weight: 100; font-size: 16px">(<?php echo count($orders);?>)</small></h1>
	    </div>
	    <table>
		    <thead>
		    <tr>
			    <th>Auftrag</th>
			    <th>Kunde</th>
			    <th>DC Montagetermin</th>
			    <th><span>Abgerechnet</span>DC</th>
			    <th><span>Abgerechnet</span>SPEICHER</th>
			    <th><span>Abgerechnet</span>AC</th>
		    </tr>
		    </thead>
		    <tbody class="d-flex flex-wrap">
			<?php
			foreach ( $orders as $order ) {
				include template( 'admin-orders-dashboard/row' );
			}
			?>
		    </tbody>
	    </table>
    </div>
</div>

<script>
  jQuery(document).ready( function($) {
    $('.billed-checkbox').on('change', function() {
      var post_id = $(this).attr( 'data-id' );
      var post_meta = $(this).attr( 'data-meta' );
      var checkbox_value = 0;

      if ($(this).is(":checked")) {
        checkbox_value = 1;
      }

      $.ajax({
        type: 'POST',
        url: ajaxurl,
        data: {
          action: 'custom_update_post',
          post_id: post_id,
          checkbox_value: checkbox_value,
          post_meta: post_meta
        }
      });
    });
  });

</script>


<style>
	thead tr {
		width: 100%;
	}
	table {
		border-spacing: 0;
	}
	table th:nth-child(1), table td:nth-child(1) {
		width: 10%;
	}
	table th:nth-child(2),table td:nth-child(2) {
		width: 40%;
	}
	table th:nth-child(3),table td:nth-child(3) {
		width: 20%;
	}
	table th:nth-child(6), table td:nth-child(6),
	table th:nth-child(4), table td:nth-child(4),
	table th:nth-child(5), table td:nth-child(5) {
		width: 10%;
		text-align: center;
	}
	.d-flex-light {
		display: flex;
	}
    table td:not(:last-child) {
        min-width: 100px;
    }
    .order-last {
        background: #efefef;
    }
    table th {
	    display: inline-table;
    }
    table th span {
	    display: block;
	    font-size: 12px;
	    font-weight: 300;
	    margin-bottom: 5px;
    }
    table th {
	    vertical-align: bottom;
    }
	input[type="checkbox"],
    input[type=checkbox]:checked::before {
		width: 2rem;
		height: 2rem;
	}
    input[type=checkbox]:checked::before  {
	    margin: -0.0875rem 0 0 -0.15rem;
    }
</style>
