<div class="container">
    <div class="row">
        <div class="col-12 col-lg-6">
			<?php include template( 'step-1/personal-info' ); ?>
        </div>
        <div class="col-12 col-lg-6">
			<?php include template( 'step-1/contact-info' ); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
			<?php include template( 'step-1/pv-information' ); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
			<?php include template( 'step-1/offer-information' ); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
			<?php include template( 'global/notes' ); ?>
        </div>
    </div>
	<?php include template( 'global/uploader' ); ?>
</div>
