<?php if ( $step === 4 ): ?>

    <div class="actions">
        <div class="col-12">
	        <button class="button-secondary" formaction="post.php?saveupload=on"><span>Speichern / Hochladen</span></button>
            <button class="button-primary right" formaction="post.php?dc_technician=on">
                <span>Montage abschließen</span>
            </button>
        </div>
    </div>

<?php endif; ?>