<?php

$filter = 'ac-defects';
$title = 'AC Nacharbeiten?';

$orderID = $order->ID;
?>

<div class="container">
	<?php if ( checkRoles( [ 'administrator', 'director', 'ac_project_manager', 'dc_project_manager' ] ) ): ?>
		<?php include template( 'global/delivery' ); ?>
	<?php endif;?>
    <div class="row justify-content-md-center">
        <div class="col-12">
            <div class="row">
                <div class="col-12">
					<?php include template( 'step-4/dc-appointment' ); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
					<?php include template( 'step-6/ac-appointment' ); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-lg-6">
					<?php include template( 'step-2/personal-and-contact-info' ); ?>
                </div>
                <div class="col-12 col-lg-6">
					<?php include template( 'step-2/pv-and-offer-info' ); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
					<?php include template( 'global/notes' ); ?>
                </div>
		        <div class="col-12">
			        <?php include template( 'global/customer-notes' ); ?>
		        </div>
            </div>
        </div>
    </div>
	<?php include template( 'global/uploader' ); ?>
	<?php if(get_current_user_id() != (int) get_post_meta( $order->ID, 'op_defect_technician', true )):?>
	<?php view( 'global/defects', compact(['filter', 'orderID', 'title']) ); ?>
	<?php endif;?>
</div>