<?php
$dcDelivery    = get_post_meta( $order->ID, 'dc_delivery', true );
$dcAppointment = get_post_meta( $order->ID, 'dc_appointment', true );
$dateFormat    = get_option( 'date_format' );
$salutation    = get_post_meta( $order->ID, 'salutation', true );
$greeting      = ( $salutation === 'Herr' ? 'geehrter' : 'geehrte' );
$name          = implode( ' ', [
	$salutation,
	get_post_meta( $order->ID, 'firstName', true ),
	get_post_meta( $order->ID, 'lastName', true ),
] );

$companyWithoutForm = utf8_decode(get_option('companyWithoutForm'));
$companyColor =  get_option( 'color' );
?>

<style>h1, h2, h3 {
        color: <?php echo $companyColor;?>;
    }

    div b {
        display: block
    }
</style>
<table style="max-width: 600px; margin: 50px auto;">
    <tr>
        <td>
	        <img src="<?php echo wp_get_attachment_url(get_option('logo'));?>" alt="" width="250">
            <br>
            <br>
            <br>
            <h1>Ihre Termine</h1>
            <h2>Sehr <?php echo $greeting; ?> <?php echo $name; ?>,</h2>
            <p>anbei erhalten Sie die vereinbarten Termine.</p>

            <div><b>Liefertermin Module</b></div>
			<?php echo date_i18n( $dateFormat, strtotime( $dcDelivery ) ); ?>
            <br/>
            <br/>
	        <strong>Bitte beachten Sie: Den Liefertermin für den Speicher erhalten Sie in einer separaten E-Mail.</strong>
	        <br/>
	        <br/>
            <div>
                <b>Montagetermin</b>
            </div>
			<?php echo date_i18n( $dateFormat, strtotime( $dcAppointment ) ); ?>
            <br>
            <p>
                Bei Fragen stehen wir Ihnen gerne zur Verfügung.
            </p>

            <b style="background: red; display: block; padding:20px; color: #fff; text-align: center; border-radius: 10px">WICHTIG!
                Den
                gelieferten Speicher
                und die dazugehörigen Akkus, bitte vor Regen & Feuchtigkeit geschützt Lagern.
                (bei Schäden durch Feuchtigkeit haftet der Kunde selbst)
            </b>
            <p>
                PS: Das im Anhang befindende Dokument für das Marktstammdatenregister dient nur als Anleitung und muss
                erst
                nach der Elektroinstallation durchgeführt werden.
            </p>
            <br>
            Mit freundlichen Grüßen<br>
	        <h2>Ihr Projektmanagement von <?php echo $companyWithoutForm; ?></h2>
        </td>
    </tr>
</table>