<?php
$salutation = get_post_meta( $order->ID, 'salutation', true );
$orderID = $order->ID;
$greating   = ( $salutation === 'Herr' ? 'geehrter' : 'geehrte' );
$name       = implode( ' ', [
	$salutation,
	get_post_meta( $order->ID, 'firstName', true ),
	get_post_meta( $order->ID, 'lastName', true ),
] );

$company = utf8_decode(get_option('company'));
$companyPhone = get_option('telefon');
$companyMail = get_option('email');
$companyWebsite = get_option('website');
$companyFax = get_option('fax');
$companyWithoutForm = utf8_decode(get_option('companyWithoutForm'));
$companyStreet = utf8_decode(get_option('street'));
$companyCity = utf8_decode(get_option('city'));
$companyZip = get_option('zip');
$companyVatId = get_option('vatid');
$companyHandelsregister = utf8_decode(get_option('handelsregister'));
$companyDirector = utf8_decode(get_option('director'));
$companyBank = utf8_decode(get_option('bank'));
$companyColor =  get_option( 'color' );

$paymentModalities = (array)json_decode(get_option('abschlag'));
?>
<style>h1, h2, h3 {
        color: <?php echo $companyColor;?>;
    }

    div b {
        display: block
    }
    .button {
        padding: 10px 30px;
        color: white;
        border-radius: 10px;
        background: <?php echo $companyColor;?>;
	    text-decoration: none;
	    display: inline-block;
    }
</style>
<table style="max-width: 600px; margin: 50px auto;">
    <tr>
        <td>
            <img src="<?php echo wp_get_attachment_url(get_option('logo'));?>" alt="" width="250">
            <br>
            <br>
            <br>
            <h1>Herzlich Willkommen bei <?php echo $companyWithoutForm; ?></h1>
            <h2>Sehr <?php echo $greating; ?> <?php echo $name; ?>,</h2>
            <p>
                wir möchten uns zunächst nochmal herzlich für das uns entgegen gebrachte Vertrauen bedanken und
                bestätigen Ihnen hiermit gerne den Eingang Ihres Auftrags.
            </p>
            <p>
                Auf Basis der im Rahmen des Auftrags gemachten Angaben haben wir eine erste technische
                Machbarkeitsprüfung mit einem positiven Ergebnis durchgeführt.
            </p>
            <p>
                Um die Umsetzung Ihres Vorhabens weiter entschlossen voranzubringen, würden wir Sie in den nächsten
                Tagen nochmals telefonisch kontaktieren, um den Installationstermin gemeinsam mit Ihnen zu koordinieren.
            </p>
            <p>
                Für Fragen vorab stehen wir Ihnen gerne telefonisch zur Verfügung.
            </p>
            <p>
                <b>Montag - Freitag von <?php echo get_option('openingHours');?></b>
            </p>
            <h2>Auftragsstatus #<?php echo $order->ID;?></h2>
	        <p>Auf unserer Webseite können Sie ganz bequem den Status Ihres Auftrages nachverfolgen.
		        Geben Sie auf der verlinkten Seite Ihre für den Auftrag angegebene Postleitzahl ein.<br><br>
		        <a class="button" href="<?php echo get_home_url()?>/auftragsstatus?order-id=<?php echo $orderID;?>">Auftragsstatus anzeigen</a>
	        </p>
	        <br>
            <h2>
                Unsere gemeinsamen Schritte in Ihre sonnige Zukunft
            </h2>
            <div>
                <p><b>1. Auftragserteilung</b>
                    Den ersten Schritt haben Sie bereits getan: Nach einer umfassenden Beratung durch unsere Fachberater
                    haben Sie sich für eine Qualitäts-Solarstromanlage entschieden.
                </p>
                <p><b>2. Technische Prüfung</b> Ihres Bauvorhabens anhand eines Simulationsprogramms durch die
                    vorhandenen
                    Bilder. Damit ermitteln wir die endgültige Dimensionierung und Optimierung Ihrer Solarstromanlage.
                </p>
                <p><b>3. Anmeldung </b>beim Energieversorgungsunternehmen (EVU) Wir melden Ihre Solarstromanlage bei
                    Ihrem
                    Netzbetreiber an – Sie müssen sich um nichts kümmern.</p>
                <p><b>4. Logistik </b>Die bestellten Komponenten werden direkt an Sie geliefert und verbaut. Sie werden
                    rechtzeitig informiert. Wir bitten Sie bei der Montage anwesend zu sein, um den Handwerkern bei
                    Fragen
                    zur Verfügung zu stehen und den Handwerkern oder Elektrikern Zugang zum Haus zu gewähren.</p>
                <p><b>5. Montage </b>Die Montage erfolgt in zwei Arbeitsschritten. Der erste Schritt ist die DC-Montage:
                    Diese beinhaltet die komplette Montage des Solar-Befestigungssystems, der Photovoltaik-Module, die
                    Verbindung der Module, die Verlegung der Solarkabel bis zum Wechselrichter o. Zählerfeld. Nach
                    Überweisung des ersten Abschlags von <?php echo array_keys($paymentModalities)[0];?>% der Bruttoauftragssumme (der 2. Abschlag von <?php echo array_keys($paymentModalities)[1];?>% ist nach der Lieferung des Speichers zu entrichten) wird der AC-Termin innerhalb der
                    nächsten 7-14 Werktage eingeplant.</p>
                <p><b>6. Elektrik </b>Der nächste Schritt ist die AC-Montage: Diese umfasst die komplette
                    Elektroinstallation vom Wechselrichter/Speicher bis zum Zählerschrank (Zählerfeld).
	                <?php if(isset(array_keys($paymentModalities)[2])) :?>
	                Die Fertigmeldung an den Netzbetreiber kann erst nach der Schlusszahlung von den restlichen <?php echo array_keys($paymentModalities)[2];?>% der Bruttoauftragssumme
                    erfolgen.</p>
	                <?php else:?>
	                Die Fertigmeldung erfolgt im Anschluss.
	                <?php endif;?>
                <p><b>7. Inbetriebnahme </b>Nach kompletter Montage der Solarstromanlage signalisieren wir Ihrem
                    Netzbetreiber durch die Fertigstellungsmeldung, dass die Anlage ans Netz genommen werden kann. Die
                    Inbetriebnahme Ihrer Solarstromanlage darf nur von einem Vertreter des Netzbetreibers erfolgen.
                    Hierzu
                    wird der Netzbetreiber oder ein von ihm bestellter Vertreter einen Termin mit Ihnen vereinbaren.</p>
                <p><b>8. Anmeldung Bundesnetzagentur/Marktstammdatenregister</b>Nun sind Sie gefragt: Die Anmeldung
                    Ihrer
                    Solarstromanlage bei der Bundesnetzagentur/Marktstammdaten-register zu registrieren. Eine
                    detaillierte
                    Beschreibung als Hilfestellung finden Sie <a
                            href="https://www.marktstammdatenregister.de/MaStRHilfe/subpages/regCheck.html">hier</a>.
            </div>
            <br>
            Mit freundlichen Grüßen<br>
            <h2>Ihr Projektmanagement von <?php echo get_option('companyWithoutForm'); ?></h2>
        </td>
    </tr>
</table>