<?php
$step                 = (int) ( $options['step'] ?? null );
$forceControllingView = (bool) ( $options['forceControllingView'] ?? false );

?>

<div class="row">
    <div class="col-12 default_list">
        <div class="dashboard__header">
			<?php if ( ! empty( $step ) ) : ?>
                <div class="step__counter step__counter--<?php echo $step;?>"><?php echo $step; ?></div>
			<?php elseif (str_contains($options['cssClass'], 'bh')) :?>
				<div class="step__counter step__counter--<?php echo $options['cssClass'];?>">BH</div>
			<?php endif; ?>
            <h1><?php echo $title; ?> <small style="font-weight: 100; font-size: 16px">(<?php echo count($orders);?>)</small></h1>
        </div>
	    <table>
		    <thead>
		    <tr>
			    <th>Auftrag</th>
			    <th>Datum</th>
			    <th>Monteur</th>
			    <th>Kunde</th>
			    <th>PLZ</th>
			    <th>kwp</th>
		    </tr>
		    </thead>
		<?php
			foreach ( $orders as $order ) {
				include template( 'dc-dashboard/row' );
			}
			?>
	    </table>
    </div>
</div>