<?php
$privilegedUser = checkRoles( [ 'administrator', 'director' ] );

$showEditAction = get_request_parameter( 'edit' ) === 'on';
$showRegistrationAction = checkRoles( [
		'registration',
		'administrator',
		'director',
	] ) && empty( get_post_meta( $order->ID, 'registration', true ) );
?>

<div class="actions">
    <div class="col-12">
	    <button class="button-secondary" formaction="post.php?saveupload=on"><span>Speichern / Hochladen</span></button>
	    <button type="submit" class="button-secondary" formaction="post.php?step_back=on">
            <span>Neuen Termin vereinbaren</span>
        </button>
        <a class="button-secondary"
           href="edit.php?post_type=customer&page=orders_spreadsheet&order-id=<?php echo $order->ID; ?>">
            Lieferliste exportieren
        </a>
		<?php if ( $privilegedUser === true ): ?>
            <button class="button-primary right"><span>Speichern</span></button>
		<?php endif; ?>
	    <?php if ( $showRegistrationAction === true && !$showEditAction ): ?>
		    <a class="button-secondary" href="<?php echo addOrUpdateUrlParam( [ 'registration' => 'on' ] ); ?>"><span>Anmeldung</span></a>
	    <?php endif; ?>
		<?php if ( $privilegedUser === true || checkRoles( 'dc_technician' ) ): ?>
            <button <?php if ( $privilegedUser === true ): ?>formaction="post.php?step_forward=on"
                    class="button-secondary<?php else: ?>button-primary<?php endif; ?> right">
                <span>Montage abschließen</span>
            </button>
		<?php endif ?>
	    <?php if ( $privilegedUser): ?>
		    <div class="secondary-actions">
			    <a href="<?php echo addOrUpdateUrlParam( [ 'reset_order' => 'on' ] ); ?>">Auftrag stornieren</a>
			    <a href="<?php echo addOrUpdateUrlParam( [ 'softreset' => 'on' ] ); ?>">Auftrag zurücksetzen</a>
		    </div>
	    <?php endif;?>
    </div>
</div>