<?php
$showRegistrationAction = checkRoles( [
		'registration',
		'administrator',
		'director',
		'registration'
	] ) && empty( get_post_meta( $order->ID, 'registration', true ) );
$showConfirmAction      = checkRoles( [ 'project_manager', 'administrator', 'director' ] );
$showEditAction = get_request_parameter( 'edit' ) === 'on';

?>

<div class="actions">
    <div class="col-12">
	    <button class="button-secondary" formaction="post.php?saveupload=on"><span>Speichern<?php echo $showEditAction ? '' : ' / Hochladen';?></span></button>
		<?php if ( $showRegistrationAction === true && !$showEditAction ): ?>
			<a class="button-secondary" href="<?php echo addOrUpdateUrlParam( [ 'registration' => 'on' ] ); ?>"><span>Anmeldung</span></a>
			<a class="button-secondary" href="<?php echo addOrUpdateUrlParam( [ 'projectPdf' => 'on' ] ); ?>">Projektierung PDF</a>
		<?php endif; ?>
		<?php if ( $showConfirmAction && !$showEditAction ) : ?>
			<a class="button-secondary" href="<?php echo addOrUpdateUrlParam( [ 'edit' => 'on' ] ); ?>">Angebot
				bearbeiten</a>
            <button class="button-primary right"><span>Bestätigen & an Montage senden</span></button>
		<?php endif; ?>
	    <?php if ($showRegistrationAction):?>
		    <div class="secondary-actions">
			    <a href="<?php echo addOrUpdateUrlParam( [ 'reset_order' => 'on' ] ); ?>">Auftrag stornieren</a>
			    <a href="<?php echo addOrUpdateUrlParam( [ 'softreset' => 'on' ] ); ?>">Auftrag zurücksetzen</a>
		    </div>
	    <?php endif;?>
    </div>
</div>