<div class="container">
	<?php if ( isset( $_GET['edit'] ) && $_GET['edit'] === 'on'  ): ?>
		<div class="row">
			<div class="col-12 col-lg-6">
				<?php include template( 'step-2/personal-info' ); ?>
			</div>
			<div class="col-12 col-lg-6">
				<?php include template( 'step-1/contact-info' ); ?>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<?php include template( 'step-1/pv-information' ); ?>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<?php include template( 'step-1/offer-information' ); ?>
			</div>
		</div>
		<input type="hidden" name="allow-edit-in-step-3" value="on"/>
	<?php else: ?>
    <div class="row">
        <div class="col-12 col-lg-6">
			<?php include template( 'step-2/personal-and-contact-info' ); ?>
        </div>
        <div class="col-12 col-lg-6">
			<?php include template( 'step-2/pv-and-offer-info' ); ?>
        </div>
    </div>
	<?php endif;?>
    <div class="row">
        <div class="col-12">
			<?php include template( 'global/notes' ); ?>
        </div>
	    <div class="col-12">
		    <?php include template( 'global/customer-notes' ); ?>
	    </div>
    </div>
	<?php include template( 'global/uploader' ); ?>
</div>